name: main

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          registry-url: https://registry.npmjs.org/

      - name: Dependencies
        run: npm ci

      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
